In [244]:
lines = None
with open('../pagerank/test1.txt') as f:
    lines = f.readlines()

In [245]:
lines = [line.strip() for line in lines]
numPages = int(lines[0])
numLinks = int(lines[1])

In [246]:
edges = [[0] * numPages for _ in range(numPages)]

In [247]:
print(edges)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [248]:
for line in lines[2:]:
    line = [int(l) for l in line.split()]
    x, y = line
    print(x, y)
    edges[x][y] = 1

0 2
0 4
0 3
4 1
1 2
1 3
2 0
3 0
3 2


In [249]:
for row in edges:
    print(row)

[0, 0, 1, 1, 1]
[0, 0, 1, 1, 0]
[1, 0, 0, 0, 0]
[1, 0, 1, 0, 0]
[0, 1, 0, 0, 0]


# TEST

In [250]:
import numpy as np

In [251]:
p = [[0.7, 0.3], [0.2, 0.8]]
x = [[0], [1]]

p = np.matrix(p)
x = np.array(x)

np.dot(p,x)

matrix([[0.3],
        [0.8]])

In [252]:
test = [[0, 0, 1, 0, 0, 0, 0], [0, 1, 1, 0, 0, 0, 0], [1, 0, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 1, 1, 0, 1]]
alpha = 0.14
n = len(test)
for r in range(len(test)):
    numOfOnes = sum(test[r])
    if numOfOnes == 0:
        for c in range(len(test[0])):
            test[r][c] = 1 / n
    else:
        for c in range(len(test[0])):
            if test[r][c] == 1:
                test[r][c] = 1/numOfOnes
test = np.matrix(test)
test = test*(1-alpha)
test = test + (alpha / n)

x = np.array([1/n for _ in range(n)])

print(x.dot(p))


ValueError: shapes (7,) and (2,2) not aligned: 7 (dim 0) != 2 (dim 0)

In [253]:
def getAdjacencyMatrix(input_file):
    lines = None
    with open('../pagerank/test1.txt') as f:
        lines = f.readlines()
    
    lines = [line.strip() for line in lines]
    numPages = int(lines[0])
    numLinks = int(lines[1])

    edges = [[0] * numPages for _ in range(numPages)]

    for line in lines[2:]:
        line = [int(l) for l in line.split()]
        x, y = line
        edges[x][y] = 1
    return edges

In [254]:
def getTransitionMatrixWithTeleporting(input_file, alpha):
    test = getAdjacencyMatrix(input_file)
    n = len(test)
    for r in range(len(test)):
        numOfOnes = sum(test[r])
        if numOfOnes == 0:
            for c in range(len(test[0])):
                test[r][c] = 1 / n
        else:
            for c in range(len(test[0])):
                if test[r][c] == 1:
                    test[r][c] = 1/numOfOnes
    test = np.matrix(test)
    test = test*(1-alpha)
    test = test + (alpha / n)
    return test

In [255]:
def getInitialVector(n):
    x = np.array([1/n for _ in range(n)])
    return x

In [256]:
transitionMatrix = getTransitionMatrixWithTeleporting('../pagerank/test1.txt', 0.14)
initialVector = getInitialVector(len(transitionMatrix))
initialVector

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [257]:
def powerIteration(x, p):
    return x.dot(p)

In [269]:
initialVector = getInitialVector(len(transitionMatrix))
for _ in range(100):
    initialVector = powerIteration(initialVector, transitionMatrix)
print(initialVector)

[[0.32060012 0.13111862 0.25208952 0.17628637 0.11990537]]


In [276]:
pageRank = initialVector.tolist()[0]
pageRankToId = [(value, i) for i, value in enumerate(pageRank)]
pageRankToId = sorted(pageRankToId, reverse = True)

for value, id in pageRankToId:
    print(f"Page id: {id}, Page rank: {value}")

Page id: 0, Page rank: 0.3206001241423446
Page id: 2, Page rank: 0.25208951531723867
Page id: 3, Page rank: 0.17628637434771935
Page id: 1, Page rank: 0.13111861727189275
Page id: 4, Page rank: 0.11990536892080549


In [198]:
test = [[0, 0, 1, 0, 0, 0, 0], [0, 1, 1, 0, 0, 0, 0], [1, 0, 1, 1, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 1, 1, 0, 1]]
alpha = 0.14

c = len(test[0])
perZero = alpha / c
for row in range(len(test)):
    numOfOnes = sum(test[row])
    numOfZeros = c - numOfOnes
    for col in range(len(test[0])):
        if test[row][col] == 0:
            test[row][col] = perZero
        else:
            test[row][col] = (1 - numOfZeros*perZero)/numOfOnes

x = [1/c for _ in range(c)]

for row in test:
    print(row)
print(x)

[0.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02]
[0.02, 0.45, 0.45, 0.02, 0.02, 0.02, 0.02]
[0.3066666666666667, 0.02, 0.3066666666666667, 0.3066666666666667, 0.02, 0.02, 0.02]
[0.02, 0.02, 0.02, 0.45, 0.45, 0.02, 0.02]
[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.88]
[0.02, 0.02, 0.02, 0.02, 0.02, 0.45, 0.45]
[0.02, 0.02, 0.02, 0.3066666666666667, 0.3066666666666667, 0.02, 0.3066666666666667]
[0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285, 0.14285714285714285]


In [199]:
p = np.matrix(test)
x = np.array(x)

In [201]:
print(x.dot(p))

[[0.06095238 0.08142857 0.2452381  0.16333333 0.12238095 0.08142857
  0.2452381 ]]


In [124]:
print(x)

[[0.14285714285714285], [0.14285714285714285], [0.14285714285714285], [0.14285714285714285], [0.14285714285714285], [0.14285714285714285], [0.14285714285714285]]


In [125]:
import numpy as np

In [145]:
p = np.matrix(test)

In [155]:
vector = np.matrix(x)
vector


matrix([[0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714]])

In [156]:
np.dot(p, vector)

matrix([[0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714],
        [0.14285714]])

In [140]:
np.dot(p, vector)

array([[0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714]])

In [147]:
print(p)

[[0.02       0.02       0.88       0.02       0.02       0.02
  0.02      ]
 [0.02       0.45       0.45       0.02       0.02       0.02
  0.02      ]
 [0.30666667 0.02       0.30666667 0.30666667 0.02       0.02
  0.02      ]
 [0.02       0.02       0.02       0.45       0.45       0.02
  0.02      ]
 [0.02       0.02       0.02       0.02       0.02       0.02
  0.88      ]
 [0.02       0.02       0.02       0.02       0.02       0.45
  0.45      ]
 [0.02       0.02       0.02       0.30666667 0.30666667 0.02
  0.30666667]]


matrix([[0.3],
        [0.8]])